

services:

  mysql:
    image: mysql:8.0.35
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      database: {}
    environment:
      MYSQL_DATABASE: datasuser
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    networks:
      database: {}
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 100M
      PMA_ABSOLUTE_URI: ""
    depends_on:
      - mysql

volumes:
  mysql:
    driver: "local"

networks:
  optimo:
    external: true
  database:
    
    external: true



